export const ROUTES = {
  HOME: '/',
  INSTAGRAM: '/instagram',
  INSTAGRAM_REELS: '/instagram/reels',
  INSTAGRAM_STORIES: '/instagram/stories',
  INSTAGRAM_POSTS: '/instagram/posts',
  FACEBOOK: '/facebook',
  YOUTUBE: '/youtube',
  YOUTUBE_VIDEO: '/youtube/video',
  YOUTUBE_SHORTS: '/youtube/shorts',
  YOUTUBE_MP3: '/youtube/mp3',
  TOOLS: '/tools',
  TOOLS_VIDEO_TO_AUDIO: '/tools/video-to-audio',
  TOOLS_CONVERTER: '/tools/converter',
  TOOLS_THUMBNAIL: '/tools/thumbnail',
  TOOLS_METADATA: '/tools/metadata',
  TOOLS_QR_TRANSFER: '/tools/qr-transfer',
  TRANSFER: '/transfer/:token',
  HOW_IT_WORKS: '/how-it-works',
  FAQ: '/faq',
  ABOUT: '/about',
  PRIVACY: '/privacy',
  TERMS: '/terms'
};
